
ALTER TABLE users ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS snils VARCHAR(14);
ALTER TABLE users ADD COLUMN IF NOT EXISTS passport_series VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS passport_number VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sms_code VARCHAR(6);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sms_code_expires TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gosuslugi_linked BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gosuslugi_data JSONB;
